import {FormFactory} from "@codingapi/ui-framework";
import {FormInput} from "./input";
import {FormPassword} from "./password";
import {FormCaptcha} from "./captcha";
import {FormCheckbox} from "./checkbox";
import {FormRadio} from "./radio";
import {FormRate} from "./rate";
import {FormSlider} from "./slider";
import {FormStepper} from "./stepper";
import {FormTextArea} from "./textarea";
import {FormSwitch} from "./switch";
import {FormDate} from "./date";
import {FormCascader} from "./cascader";
import {FormSelect} from "./select";
import {FormSelector} from "./selector";
import {FormUploader} from "./uploder";
import {FormColor} from "./color";
import {FormCode} from "./code";

FormFactory.getInstance().addItem('input',FormInput);
FormFactory.getInstance().addItem('password',FormPassword);
FormFactory.getInstance().addItem('captcha',FormCaptcha);
FormFactory.getInstance().addItem('checkbox',FormCheckbox);
FormFactory.getInstance().addItem('radio',FormRadio);
FormFactory.getInstance().addItem('rate',FormRate);
FormFactory.getInstance().addItem('slider',FormSlider);
FormFactory.getInstance().addItem('stepper',FormStepper);
FormFactory.getInstance().addItem('textarea',FormTextArea);
FormFactory.getInstance().addItem('switch',FormSwitch);
FormFactory.getInstance().addItem('date',FormDate);
FormFactory.getInstance().addItem('cascader',FormCascader);
FormFactory.getInstance().addItem('select',FormSelect);
FormFactory.getInstance().addItem('selector',FormSelector);
FormFactory.getInstance().addItem('uploader',FormUploader);
FormFactory.getInstance().addItem('color',FormColor);
FormFactory.getInstance().addItem('code',FormCode);
